=== dbru540/powerbi-mcp-designer/powerbi_mcp/validation/schemas/fabric__item__report__definition__report__3.0.0__schema.json
{
  "$id": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/report/3.0.0/schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Report",
  "description": "Defines a report and its pages, visuals, settings, and additional information.",
  "type": "object",
  "properties": {
    "$schema": {
      "description": "Defines the schema to use for an item.",
      "type": "string",
      "const": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/report/3.0.0/schema.json"
    },
    "themeCollection": {
      "$ref": "#/definitions/ThemeCollection",
      "description": "Define a theme (built-in and/or a custom theme) to be used for this report."
    },
    "filterConfig": {
      "description": "Filters that apply to the entire report (all pages and all visuals).",
      "$ref": "../../filterConfiguration/1.2.0/schema-embedded.json"
    },
    "objects": {
      "description": "Specifies the formatting to be set for different \"objects\" of a report.",
      "$ref": "#/definitions/ReportFormattingObjects"
    },
    "reportSource": {
      "description": "Defines how the report was created.",
      "type": "string",
      "anyOf": [
        {
          "const": "Default",
          "description": "A blank report generated by Power BI apps."
        },
        {
          "const": "SharePoint",
          "description": "A quick create report created from a SharePointList."
        },
        {
          "const": "Teams",
          "description": "A quick create report created from Teams."
        },
        {
          "const": "QuickCreate",
          "description": "A quick create report created from Power BI app."
        },
        {
          "const": "EmbedQuickCreate",
          "description": "A quick create report created from an embedded source."
        },
        {
          "const": "Datamart",
          "description": "A new report created from Datamart."
        },
        {
          "const": "DataExplore",
          "description": "A report generated by exporting an Exploration as a report."
        }
      ]
    },
    "publicCustomVisuals": {
      "description": "Names of the custom visuals used in this report from AppSource.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "resourcePackages": {
      "description": "Set of resources used within this report.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/ResourcePackage"
      }
    },
    "organizationCustomVisuals": {
      "description": "Names and metadata of the organization approved custom visuals used in the report.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/OrganizationCustomVisual"
      }
    },
    "annotations": {
      "description": "Additional information to be saved (for example comments, readme, etc) for this report.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Annotation"
      }
    },
    "dataSourceVariables": {
      "description": "A string containing the state of any variables from the underlying direct query data source that should be overridden when rendering this content.\nData source variables do not supply values for M parameters in the semantic model. Instead, data source variables are applied when accessing the underlying direct query source.",
      "type": "string"
    },
    "settings": {
      "description": "Settings for the report.",
      "$ref": "#/definitions/ExplorationSettings"
    },
    "slowDataSourceSettings": {
      "description": "Settings for slow data sources (for example turning all apply all button for filters).",
      "$ref": "#/definitions/ExplorationSlowDataSourceSettings"
    }
  },
  "additionalProperties": false,
  "required": [
    "$schema",
    "themeCollection"
  ],
  "definitions": {
    "ThemeCollection": {
      "type": "object",
      "properties": {
        "baseTheme": {
          "description": "Defines the base monthly release themes shipped with Power BI.",
          "$ref": "#/definitions/ThemeMetadata"
        },
        "customTheme": {
          "description": "Defines a custom theme that is applied on top of the base theme.\nProperties not defined in the custom theme will fallback to using the base theme.",
          "$ref": "#/definitions/ThemeMetadata"
        }
      },
      "additionalProperties": false
    },
    "ThemeMetadata": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the theme.",
          "type": "string"
        },
        "reportVersionAtImport": {
          "$ref": "#/definitions/ThemeVersion",
          "description": "Versions when the theme was added to the report."
        },
        "type": {
          "$ref": "#/definitions/ThemeResourcePackageType",
          "description": "Built-in or user specific custom theme."
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "reportVersionAtImport",
        "type"
      ]
    },
    "ThemeVersion": {
      "type": "object",
      "properties": {
        "visual": {
          "description": "The max visual container version at import.",
          "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$",
          "type": "string"
        },
        "page": {
          "description": "The max page version at import.",
          "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$",
          "type": "string"
        },
        "report": {
          "description": "The max report version at import.",
          "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "page",
        "report",
        "visual"
      ]
    },
    "ThemeResourcePackageType": {
      "type": "string",
      "anyOf": [
        {
          "const": "RegisteredResources",
          "description": "Additional resources not bundled as part of the Power BI application."
        },
        {
          "const": "SharedResources",
          "description": "Resources bundled as part of the Power BI applications."
        }
      ]
    },
    "ReportFormattingObjects": {
      "type": "object",
      "properties": {
        "outspacePane": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "selector": {
                "description": "Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.",
                "$ref": "../../formattingObjectDefinitions/1.4.0/schema.json#/definitions/Selector"
              },
              "properties": {
                "$ref": "#/definitions/OutspacePane",
                "description": "Describes the properties of the object to apply formatting changes to."
              }
            },
            "additionalProperties": false,
            "required": [
              "properties"
            ]
          }
        },
        "section": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "selector": {
                "description": "Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.",
                "$ref": "../../formattingObjectDefinitions/1.4.0/schema.json#/definitions/Selector"
              },
              "properties": {
                "$ref": "#/definitions/Section",
                "description": "Describes the properties of the object to apply formatting changes to."
              }
            },
            "additionalProperties": false,
            "required": [
              "properties"
            ]
          }
        }
      },
      "additionalProperties": false
    },
    "OutspacePane": {
      "type": "object",
      "properties": {
        "expanded": {},
        "visible": {}
      },
      "additionalProperties": false
    },
    "Section": {
      "type": "object",
      "properties": {
        "verticalAlignment": {}
      },
      "additionalProperties": false
    },
    "ResourcePackage": {
      "type": "object",
      "properties": {
        "id": {
          "type": "number"
        },
        "name": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/ResourcePackageType"
        },
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ResourcePackageItem"
          }
        },
        "disabled": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "required": [
        "items",
        "name",
        "type"
      ]
    },
    "ResourcePackageType": {
      "type": "string",
      "anyOf": [
        {
          "const": "CustomVisual"
        },
        {
          "const": "RegisteredResources"
        },
        {
          "const": "SharedResources"
        },
        {
          "const": "OrganizationalStoreCustomVisual"
        }
      ]
    },
    "ResourcePackageItem": {
      "type": "object",
      "properties": {
        "id": {
          "type": "number"
        },
        "name": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/ResourcePackageItemType"
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "path",
        "type"
      ]
    },
    "ResourcePackageItemType": {
      "type": "string",
      "anyOf": [
        {
          "const": "CustomVisualJavascript"
        },
        {
          "const": "CustomVisualsCss"
        },
        {
          "const": "CustomVisualScreenshot"
        },
        {
          "const": "CustomVisualIcon"
        },
        {
          "const": "CustomVisualWatermark"
        },
        {
          "const": "CustomVisualMetadata"
        },
        {
          "const": "Image"
        },
        {
          "const": "ShapeMap"
        },
        {
          "const": "CustomTheme"
        },
        {
          "const": "BaseTheme"
        },
        {
          "const": "DashboardTheme"
        },
        {
          "const": "DashboardBaseTheme"
        },
        {
          "const": "HighContrastTheme"
        },
        {
          "const": "AppNavigation"
        },
        {
          "const": "AppTheme"
        },
        {
          "const": "AppBaseTheme"
        }
      ]
    },
    "OrganizationCustomVisual": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the organization custom visual.",
          "type": "string"
        },
        "path": {
          "description": "Path where the custom visual is stored.",
          "type": "string"
        },
        "disabled": {
          "description": "Signifies if the custom visual is disabled by the organization.",
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "path"
      ]
    },
    "Annotation": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Unique name for the annotation.",
          "type": "string"
        },
        "value": {
          "description": "A value for this annotation.",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "value"
      ]
    },
    "ExplorationSettings": {
      "type": "object",
      "properties": {
        "isPersistentUserStateDisabled": {
          "description": "Disable saving state of changes to a report as report viewers modify slicers and filters.",
          "type": "boolean"
        },
        "hideVisualContainerHeader": {
          "description": "Hide visual container header in view mode of the report.",
          "type": "boolean"
        },
        "useStylableVisualContainerHeader": {
          "description": "Use the new visual container header that is formattable.",
          "type": "boolean"
        },
        "exportDataMode": {
          "description": "When exporting data, what should be exported.",
          "type": "string",
          "anyOf": [
            {
              "const": "AllowSummarized",
              "description": "Only allow summarized data."
            },
            {
              "const": "AllowSummarizedAndUnderlying",
              "description": "Allow underlying and summarized data."
            },
            {
              "const": "None",
              "description": "Don't allow exporting data."
            }
          ]
        },
        "isReportAnnotationsDisabled": {
          "description": "Commenting is disabled for this report.",
          "type": "boolean"
        },
        "defaultFilterActionIsDataFilter": {
          "description": "When selecting data points on a visual, it will result in apply that selection as a filter instead of a highlight on other visuals.",
          "type": "boolean"
        },
        "defaultDrillFilterOtherVisuals": {
          "description": "When another visual is drilled, if visual interactions are enabled between the two visuals, then this property specifies if that drill should be applied as a filter to this visual.\nCan be overridden by setting on individual visuals.",
          "type": "boolean"
        },
        "useCrossReportDrillthrough": {
          "description": "Allow drill-through from other reports to this report.",
          "type": "boolean"
        },
        "allowChangeFilterTypes": {
          "description": "Disables changing the type of filter in view mode.",
          "type": "boolean"
        },
        "allowInlineExploration": {
          "description": "Allows personalize this visual for the report in view mode.",
          "type": "boolean"
        },
        "useEnhancedTooltips": {
          "description": "Uses better tooltips for the visuals in this report.",
          "type": "boolean"
        },
        "useScaledTooltips": {
          "description": "If enabled, the tooltip will scale to match canvas zoom.",
          "type": "boolean"
        },
        "filterPaneHiddenInEditMode": {
          "description": "Hide the filter pane in view mode.",
          "type": "boolean"
        },
        "disableFilterPaneSearch": {
          "description": "Disables the search bar in filter pane.",
          "type": "boolean"
        },
        "pagesPosition": {
          "description": "Default location where the page navigator is shown.",
          "type": "string",
          "anyOf": [
            {
              "const": "PagesPane",
              "description": "In a pane next to the report."
            },
            {
              "const": "Bottom",
              "description": "In a toolbar below the report."
            }
          ]
        },
        "allowAutomatedInsightsNotification": {
          "description": "Allow generating insights for the report in the background on data refresh.",
          "type": "boolean"
        },
        "useDefaultAggregateDisplayName": {
          "description": "Show the default aggregate in display names for summarized data.",
          "type": "boolean"
        },
        "enableDeveloperMode": {
          "description": "Enables developer mode for testing private custom visuals.",
          "type": "boolean"
        },
        "pauseQueries": {
          "description": "Allows pausing queries while making changes to a visual, so every change doesn't trigger a query.\nParticularly useful with slow data sources.",
          "type": "boolean"
        },
        "queryLimitOption": {
          "description": "Describes the limitations for how long and how much compute a single query can be allowed to consume.\nMore details for different options: https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-set-visual-query-limits",
          "type": "string",
          "anyOf": [
            {
              "const": "None"
            },
            {
              "const": "Shared"
            },
            {
              "const": "Premium"
            },
            {
              "const": "SQLServerAS"
            },
            {
              "const": "AzureAS"
            },
            {
              "const": "Custom"
            },
            {
              "const": "Auto"
            }
          ]
        },
        "customMemoryLimit": {
          "description": "If custom query limit is applied, this value defines the memory limit.",
          "type": "string"
        },
        "customTimeoutLimit": {
          "description": "If custom query limit is applied, this value defines the timeout limit.",
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "ExplorationSlowDataSourceSettings": {
      "type": "object",
      "properties": {
        "isCrossHighlightingDisabled": {
          "description": "Disable cross highlights.",
          "type": "boolean"
        },
        "isSlicerSelectionsButtonEnabled": {
          "description": "Adds 'apply' button to slicers.",
          "type": "boolean"
        },
        "isFilterSelectionsButtonEnabled": {
          "description": "Adds 'apply' button to filters.",
          "type": "boolean"
        },
        "isFieldWellButtonEnabled": {
          "description": "Adds 'apply' button to field changes.",
          "type": "boolean"
        },
        "isApplyAllButtonEnabled": {
          "description": "Adds an apply all button.",
          "type": "boolean"
        }
      },
      "additionalProperties": false
    }
  }
}

=== dbru540/powerbi-mcp-designer/example/Focus.Report/definition/report.json
{
  "$schema": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/report/3.0.0/schema.json",
  "themeCollection": {
    "baseTheme": {
      "name": "CY19SU06",
      "reportVersionAtImport": {
        "visual": "1.8.41",
        "report": "2.0.41",
        "page": "1.3.41"
      },
      "type": "SharedResources"
    },
    "customTheme": {
      "name": "FiveForty5580288424017721.json",
      "reportVersionAtImport": {
        "visual": "1.8.44",
        "report": "2.0.44",
        "page": "1.3.44"
      },
      "type": "RegisteredResources"
    }
  },
  "filterConfig": {
    "filterSortOrder": "Custom"
  },
  "objects": {
    "outspacePane": [
      {
        "properties": {
          "expanded": {
            "expr": {
              "Literal": {
                "Value": "true"
              }
            }
          }
        }
      }
    ]
  },
  "publicCustomVisuals": [
    "acterysReportingxPnA",
    "AdvancedColumnBarChart149CBDF1945A4455952D90C68DD649AA",
    "calendarVisual74934D05B71F4C31B0F79D925EE89638",
    "cdRegressionChartFEDFE3FECE5F4724A9EAF1D1F0D509A3",
    "cylindricalGauge73A12A442345453EB69B593649C3A341",
    "GanttChart4C3653EFFFEB4E7DA5A699CE198391E2",
    "GanttChartByMAQSoftware1448688115701",
    "HierarchicalTreeF39DAE8D57A743EF89F5C3809DEE2B67",
    "HierarchySlicer1458836712039",
    "HorizontalFunnel1449177164235",
    "InforiverCharts582F6C55AB6442EF8FA129089285CB47",
    "kpiTicker492C9305B9464241B52382527F977DE1",
    "linearGauge2EBA8C0A99F94BF297BCCB1CF5427E68",
    "overlappingcolumnchart294CA4C4E467CD956C919E26EF459300",
    "paretoEDD8E69761BA4B7BB3AA6D813990D7BF",
    "PBI_3AGSystems_0B9C9FBA_15A2_4A94_8AE4_8F778869B192",
    "PBI_CV_3C80B1F2_09AF_4123_8E99_C3CBC46B23E0",
    "PBI_CV_9272D058_BEA0_476A_B090_A712545F92FA",
    "planningGridA86B787D407F4AE99B016A8E5AC0A27E",
    "timelineD7EACB3A04E64A5FA9D86F6E035F3523",
    "variance8E4BB1B41A8942A7B897C7014A6E1F56",
    "waterfall6C9ED82ABD1F44C4A0D590CE01EB5EE7",
    "wishyoulizationbarchartrace",
    "wishyoulizationwalkers",
    "zebraBiCards2C860CFAA9944091B75F0DBD117F20FA"
  ],
  "resourcePackages": [
    {
      "name": "AdvancedColumnBarChart149CBDF1945A4455952D90C68DD649AA",
      "type": "CustomVisual",
      "items": [
        {
          "name": "AdvancedColumnBarChart149CBDF1945A4455952D90C68DD649AA.pbiviz.json",
          "path": "AdvancedColumnBarChart149CBDF1945A4455952D90C68DD649AA.pbiviz.json",
          "type": "CustomVisualMetadata"
        }
      ]
    },
    {
      "name": "calendarVisual74934D05B71F4C31B0F79D925EE89638",
      "type": "CustomVisual",
      "items": [
        {
          "name": "calendarVisual74934D05B71F4C31B0F79D925EE89638.pbiviz.json",
          "path": "calendarVisual74934D05B71F4C31B0F79D925EE89638.pbiviz.json",
          "type": "CustomVisualMetadata"
        }
      ]
    },
    {
      "name": "CalendarVisualA45056645E4E428B9D26EF971839A6B5",
      "type": "CustomVisual",
      "items": [
        {
          "name": "CalendarVisualA45056645E4E428B9D26EF971839A6B5.pbiviz.json",
          "path": "CalendarVisualA45056645E4E428B9D26EF971839A6B5.pbiviz.json",
          "type": "CustomVisualMetadata"
        }
      ]
    },
    {
      "name": "GanttChart4C3653EFFFEB4E7DA5A699CE198391E2",
      "type": "CustomVisual",
      "items": [
        {
          "name": "GanttChart4C3653EFFFEB4E7DA5A699CE198391E2.pbiviz.json",
          "path": "GanttChart4C3653EFFFEB4E7DA5A699CE198391E2.pbiviz.json",
          "type": "CustomVisualMetadata"
        }
      ]
    },
    {
      "name": "GanttChartByMAQSoftware1448688115701",
      "type": "CustomVisual",
      "items": [
        {
          "name": "GanttChartByMAQSoftware1448688115701.pbiviz.json",
          "path": "GanttChartByMAQSoftware1448688115701.pbiviz.json",
          "type": "CustomVisualMetadata"
        }
      ]
    },
    {
      "name": "HierarchicalTreeF39DAE8D57A743EF89F5C3809DEE2B67",
      "type": "CustomVisual",
      "items": [
        {
          "name": "HierarchicalTreeF39DAE8D57A743EF89F5C3809DEE2B67.pbiviz.json",
          "path": "HierarchicalTreeF39DAE8D57A743EF89F5C3809DEE2B67.pbiviz.json",
          "type": "CustomVisualMetadata"
        }
      ]
    },
    {
      "name": "HierarchySlicer1458836712039",
      "type": "CustomVisual",
      "items": [
        {
          "name": "HierarchySlicer1458836712039.pbiviz.json",
          "path": "HierarchySlicer1458836712039.pbiviz.json",
          "type": "CustomVisualMetadata"
        }
      ]
    },
    {
      "name": "linearGauge2EBA8C0A99F94BF297BCCB1CF5427E68",
      "type": "CustomVisual",
      "items": [
        {
          "name": "linearGauge2EBA8C0A99F94BF297BCCB1CF5427E68.pbiviz.json",
          "path": "linearGauge2EBA8C0A99F94BF297BCCB1CF5427E68.pbiviz.json",
          "type": "CustomVisualMetadata"
        }
      ]
    },
    {
      "name": "PBI_CV_3C80B1F2_09AF_4123_8E99_C3CBC46B23E0",
      "type": "CustomVisual",
      "items": [
        {
          "name": "PBI_CV_3C80B1F2_09AF_4123_8E99_C3CBC46B23E0.pbiviz.json",
          "path": "PBI_CV_3C80B1F2_09AF_4123_8E99_C3CBC46B23E0.pbiviz.json",
          "type": "CustomVisualMetadata"
        }
      ]
    },
    {
      "name": "textFilter25A4896A83E0487089E2B90C9AE57C8A",
      "type": "CustomVisual",
      "items": [
        {
          "name": "textFilter25A4896A83E0487089E2B90C9AE57C8A.pbiviz.json",
          "path": "textFilter25A4896A83E0487089E2B90C9AE57C8A.pbiviz.json",
          "type": "CustomVisualMetadata"
        }
      ]
    },
    {
      "name": "wishyoulizationbarchartrace",
      "type": "CustomVisual",
      "items": [
        {
          "name": "wishyoulizationbarchartrace.pbiviz.json",
          "path": "wishyoulizationbarchartrace.pbiviz.json",
          "type": "CustomVisualMetadata"
        }
      ]
    },
    {
      "name": "wishyoulizationwalkers",
      "type": "CustomVisual",
      "items": [
        {
          "name": "wishyoulizationwalkers.pbiviz.json",
          "path": "wishyoulizationwalkers.pbiviz.json",
          "type": "CustomVisualMetadata"
        }
      ]
    },
    {
      "name": "WordCloud1447959067750",
      "type": "CustomVisual",
      "items": [
        {
          "name": "WordCloud1447959067750.pbiviz.json",
          "path": "WordCloud1447959067750.pbiviz.json",
          "type": "CustomVisualMetadata"
        }
      ]
    },
    {
      "name": "RegisteredResources",
      "type": "RegisteredResources",
      "items": [
        {
          "name": "2025-06-10_14-59-0329693445723803157.jpg",
          "path": "2025-06-10_14-59-0329693445723803157.jpg",
          "type": "Image"
        },
        {
          "name": "2025-06-10_19-49-204166557638841517.jpg",
          "path": "2025-06-10_19-49-204166557638841517.jpg",
          "type": "Image"
        },
        {
          "name": "2025-06-10_19-49-5819708698410521552.jpg",
          "path": "2025-06-10_19-49-5819708698410521552.jpg",
          "type": "Image"
        },
        {
          "name": "2025-06-10_19-49-588045808087417587.jpg",
          "path": "2025-06-10_19-49-588045808087417587.jpg",
          "type": "Image"
        },
        {
          "name": "2025-06-10_19-49-589936564066043289.jpg",
          "path": "2025-06-10_19-49-589936564066043289.jpg",
          "type": "Image"
        },
        {
          "name": "2025-06-11_16-50-335217148787700067.jpg",
          "path": "2025-06-11_16-50-335217148787700067.jpg",
          "type": "Image"
        },
        {
          "name": "FiveForty5580288424017721.json",
          "path": "FiveForty5580288424017721.json",
          "type": "Image"
        },
        {
          "name": "logo_high_(1)4881384213490376.jpg",
          "path": "logo_high_(1)4881384213490376.jpg",
          "type": "Image"
        }
      ]
    },
    {
      "name": "SharedResources",
      "type": "SharedResources",
      "items": [
        {
          "name": "CY19SU06",
          "path": "BaseThemes/CY19SU06.json",
          "type": "BaseTheme"
        }
      ]
    }
  ],
  "settings": {
    "useStylableVisualContainerHeader": true,
    "exportDataMode": "AllowSummarized",
    "defaultDrillFilterOtherVisuals": true,
    "useEnhancedTooltips": true
  },
  "slowDataSourceSettings": {
    "isCrossHighlightingDisabled": false,
    "isSlicerSelectionsButtonEnabled": false,
    "isFilterSelectionsButtonEnabled": false,
    "isFieldWellButtonEnabled": false,
    "isApplyAllButtonEnabled": false
  }
}
