=== dbru540/powerbi-mcp-designer/powerbi_mcp/validation/schemas/fabric__item__report__definition__visualContainer__2.4.0__schema.json
{
  "$id": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualContainer/2.4.0/schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Visual container",
  "description": "Defines a single visual or visual group on a report page.",
  "type": "object",
  "properties": {
    "$schema": {
      "description": "Defines the schema to use for an item.",
      "type": "string",
      "const": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualContainer/2.4.0/schema.json"
    },
    "name": {
      "description": "A unique identifier for the visual across the whole page.",
      "maxLength": 50,
      "type": "string"
    },
    "position": {
      "$ref": "#/definitions/VisualContainerPosition",
      "description": "Defines where the visual is position on the page and how big it should be, along\nwith z-index (stacking) for that visual.\nAlso defines the order in which visuals are navigated when using just keyboard (tabOrder)."
    },
    "visual": {
      "description": "Defines a chart to be shown inside of this container.",
      "$ref": "../../visualConfiguration/2.2.0/schema-embedded.json"
    },
    "visualGroup": {
      "description": "Defines that this container should be used as a grouping container.",
      "$ref": "#/definitions/VisualGroupConfig"
    },
    "parentGroupName": {
      "description": "Name of the parent group (visual container), if it is part of one.",
      "type": "string"
    },
    "filterConfig": {
      "description": "Filters that apply to all this visual - on top of the filters defined for the report and page.",
      "$ref": "../../filterConfiguration/1.2.0/schema-embedded.json"
    },
    "isHidden": {
      "description": "Marks the visual as hidden.",
      "type": "boolean"
    },
    "annotations": {
      "description": "Additional information to be saved (for example comments, readme, etc) for this visual.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Annotation"
      }
    },
    "howCreated": {
      "description": "Source of creation of this visual.",
      "type": "string",
      "anyOf": [
        {
          "const": "Default",
          "description": "Used when it doesn't fall in any of the buckets below."
        },
        {
          "const": "Copilot",
          "description": "Created by copilot."
        },
        {
          "const": "CheckboxTickedInFieldList",
          "description": "Selecting data from field list."
        },
        {
          "const": "DraggedToCanvas",
          "description": "Dragging data from field list to the canvas."
        },
        {
          "const": "VisualTypeIconClicked",
          "description": "Clicking a specific visual icon in visualizations list."
        },
        {
          "const": "DraggedToFieldWell",
          "description": "Dragging data from field list to field wells."
        },
        {
          "const": "InsertVisualButton",
          "description": "Clicking the \"Insert visual\" button in ribbon."
        },
        {
          "const": "WhatIfParameterControl",
          "description": "Automatically by what-if parameter."
        },
        {
          "const": "QnaAppBar",
          "description": "Ask a question in app bar."
        },
        {
          "const": "QnaDoubleClick",
          "description": "Double clicking on the canvas to generate a Q&A visual."
        },
        {
          "const": "QnaKeyboardShortcut",
          "description": "Use keyboard shortcut for Q&A visual."
        },
        {
          "const": "FieldParameterControl",
          "description": "Automatically by field parameters."
        },
        {
          "const": "CanvasBackgroundContextMenu",
          "description": "Using on-object context menu for the canvas."
        },
        {
          "const": "ContextMenuPaste",
          "description": "By using paste from context manu."
        },
        {
          "const": "CopyPaste",
          "description": "By using copy paste."
        },
        {
          "const": "SummarizeVisualContainer",
          "description": "By using context menu Summarize."
        }
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "$schema",
    "name",
    "position"
  ],
  "definitions": {
    "VisualContainerPosition": {
      "type": "object",
      "properties": {
        "x": {
          "description": "Horizontal position of the left edge of the visual.\nShould be between 0 and width of the containing page.",
          "type": "number"
        },
        "y": {
          "description": "Vertical position of the top edge of the visual.\nShould be between 0 and height of the containing page.",
          "type": "number"
        },
        "z": {
          "description": "Defines the stacking order for the visual.\nHigher z-index visuals are shown on top of the lower ones.",
          "type": "number"
        },
        "height": {
          "description": "Height of the visual.\ny + height should be less than the height of the containing page.",
          "type": "number"
        },
        "width": {
          "description": "Width of the visual.\nx + width should be less than the width of the containing page.",
          "type": "number"
        },
        "tabOrder": {
          "description": "Defines the selection order for this visual when using keyboard (tab key)\nto navigate the visuals on the containing page.",
          "type": "number"
        },
        "angle": {
          "type": "number"
        }
      },
      "additionalProperties": false,
      "required": [
        "height",
        "width",
        "x",
        "y"
      ]
    },
    "VisualGroupConfig": {
      "type": "object",
      "properties": {
        "displayName": {
          "description": "Display name for the group.",
          "type": "string"
        },
        "groupMode": {
          "$ref": "#/definitions/GroupLayoutMode",
          "description": "Defines how the visuals are organized inside this group."
        },
        "objects": {
          "description": "Specifies the formatting to be set for different \"objects\" of this group.",
          "$ref": "#/definitions/VisualGroupFormattingObjects"
        }
      },
      "additionalProperties": false,
      "required": [
        "displayName",
        "groupMode"
      ]
    },
    "GroupLayoutMode": {
      "type": "string",
      "anyOf": [
        {
          "const": "ScaleMode",
          "description": "Visuals are scaled as group resizes to preserve the aspect ratio and avoid scrolling."
        },
        {
          "const": "ScrollMode",
          "description": "Visuals are not resized, if the containing box for group is smaller than the space\nneeded for visuals, then scrollbar is added."
        }
      ]
    },
    "VisualGroupFormattingObjects": {
      "type": "object",
      "properties": {
        "background": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "selector": {
                "description": "Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.",
                "$ref": "../../formattingObjectDefinitions/1.4.0/schema.json#/definitions/Selector"
              },
              "properties": {
                "$ref": "../../visualConfiguration/2.2.0/schema-embedded.json#/definitions/Background",
                "description": "Describes the properties of the object to apply formatting changes to."
              }
            },
            "additionalProperties": false,
            "required": [
              "properties"
            ]
          }
        },
        "lockAspect": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "selector": {
                "description": "Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.",
                "$ref": "../../formattingObjectDefinitions/1.4.0/schema.json#/definitions/Selector"
              },
              "properties": {
                "$ref": "../../visualConfiguration/2.2.0/schema-embedded.json#/definitions/LockAspect",
                "description": "Describes the properties of the object to apply formatting changes to."
              }
            },
            "additionalProperties": false,
            "required": [
              "properties"
            ]
          }
        },
        "general": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "selector": {
                "description": "Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.",
                "$ref": "../../formattingObjectDefinitions/1.4.0/schema.json#/definitions/Selector"
              },
              "properties": {
                "$ref": "#/definitions/VisualGroupGeneralFormattingObjects",
                "description": "Describes the properties of the object to apply formatting changes to."
              }
            },
            "additionalProperties": false,
            "required": [
              "properties"
            ]
          }
        }
      },
      "additionalProperties": false
    },
    "VisualGroupGeneralFormattingObjects": {
      "type": "object",
      "properties": {
        "x": {},
        "y": {},
        "width": {},
        "height": {},
        "altText": {}
      },
      "additionalProperties": false
    },
    "Annotation": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Unique name for the annotation.",
          "type": "string"
        },
        "value": {
          "description": "A value for this annotation.",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "value"
      ]
    }
  },
  "oneOf": [
    {
      "required": [
        "visual"
      ]
    },
    {
      "required": [
        "visualGroup"
      ]
    }
  ]
}

=== dbru540/powerbi-mcp-designer/example/Focus.Report/definition/pages/ReportSectiond5a9be7e10078cea179d/visuals/cb44b4aec0419f067d56/visual.json
{
  "$schema": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualContainer/2.4.0/schema.json",
  "name": "cb44b4aec0419f067d56",
  "position": {
    "x": 27,
    "y": 542,
    "z": 14000,
    "height": 165,
    "width": 236,
    "tabOrder": 14000
  },
  "visual": {
    "visualType": "pieChart",
    "query": {
      "queryState": {
        "Category": {
          "projections": [
            {
              "field": {
                "Column": {
                  "Expression": {
                    "SourceRef": {
                      "Entity": "Budget"
                    }
                  },
                  "Property": "Area lvl 2"
                }
              },
              "queryRef": "Budget.Area lvl 2",
              "nativeQueryRef": "Area lvl 2",
              "active": true
            }
          ]
        },
        "Y": {
          "projections": [
            {
              "field": {
                "Measure": {
                  "Expression": {
                    "SourceRef": {
                      "Entity": "Budget"
                    }
                  },
                  "Property": "Remaining budget per remaining CY months"
                }
              },
              "queryRef": "Budget.Remaining budget per remaining CY months",
              "nativeQueryRef": "Remaining budget per remaining CY months"
            }
          ]
        }
      },
      "sortDefinition": {
        "sort": [
          {
            "field": {
              "Measure": {
                "Expression": {
                  "SourceRef": {
                    "Entity": "Budget"
                  }
                },
                "Property": "Remaining budget per remaining CY months"
              }
            },
            "direction": "Descending"
          }
        ],
        "isDefaultSort": true
      }
    },
    "objects": {
      "labels": [
        {
          "properties": {
            "labelStyle": {
              "expr": {
                "Literal": {
                  "Value": "'Data'"
                }
              }
            }
          }
        }
      ],
      "legend": [
        {
          "properties": {
            "show": {
              "expr": {
                "Literal": {
                  "Value": "false"
                }
              }
            },
            "showTitle": {
              "expr": {
                "Literal": {
                  "Value": "false"
                }
              }
            },
            "position": {
              "expr": {
                "Literal": {
                  "Value": "'Top'"
                }
              }
            }
          }
        }
      ]
    },
    "visualContainerObjects": {
      "title": [
        {
          "properties": {
            "show": {
              "expr": {
                "Literal": {
                  "Value": "false"
                }
              }
            },
            "text": {
              "expr": {
                "Literal": {
                  "Value": "''"
                }
              }
            }
          }
        }
      ]
    },
    "drillFilterOtherVisuals": true
  },
  "filterConfig": {
    "filters": [
      {
        "name": "Filterf734571009bbea940c70",
        "field": {
          "Column": {
            "Expression": {
              "SourceRef": {
                "Entity": "DevOps_Timesheets"
              }
            },
            "Property": "Comment"
          }
        },
        "type": "Categorical",
        "howCreated": "User",
        "isHiddenInViewMode": true
      },
      {
        "name": "Filtere6ef7d3ae8c8abace217",
        "field": {
          "Column": {
            "Expression": {
              "SourceRef": {
                "Entity": "DevOps_Timesheets"
              }
            },
            "Property": "RecordDate"
          }
        },
        "type": "Categorical",
        "howCreated": "User",
        "isHiddenInViewMode": true
      },
      {
        "name": "Filter97dc7be6d81635007803",
        "field": {
          "Column": {
            "Expression": {
              "SourceRef": {
                "Entity": "Power BI - All projects"
              }
            },
            "Property": "State"
          }
        },
        "type": "Categorical",
        "howCreated": "User",
        "isHiddenInViewMode": true
      },
      {
        "name": "Filterfedbe1d2be9d618927fc",
        "field": {
          "Column": {
            "Expression": {
              "SourceRef": {
                "Entity": "Power BI - All projects"
              }
            },
            "Property": "Title"
          }
        },
        "type": "Categorical",
        "howCreated": "User",
        "isHiddenInViewMode": true
      },
      {
        "name": "Filter3221213e3397fafa4df1",
        "field": {
          "Column": {
            "Expression": {
              "SourceRef": {
                "Entity": "Power BI - All projects"
              }
            },
            "Property": "Link"
          }
        },
        "type": "Categorical",
        "howCreated": "User",
        "isHiddenInViewMode": true
      },
      {
        "name": "Filter56a7e6964c43b57685ae",
        "field": {
          "Measure": {
            "Expression": {
              "SourceRef": {
                "Entity": "DevOps_Timesheets"
              }
            },
            "Property": "Time"
          }
        },
        "type": "Advanced",
        "howCreated": "User",
        "isHiddenInViewMode": true
      }
    ]
  }
}

=== dbru540/powerbi-mcp-designer/example/Focus.Report/definition/pages/ReportSectiond5a9be7e10078cea179d/visuals/7cada50928f390e096ba/visual.json
{
  "$schema": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualContainer/2.4.0/schema.json",
  "name": "7cada50928f390e096ba",
  "position": {
    "x": 27,
    "y": 315,
    "z": 8000,
    "height": 188,
    "width": 246,
    "tabOrder": 8000
  },
  "visual": {
    "visualType": "pieChart",
    "query": {
      "queryState": {
        "Category": {
          "projections": [
            {
              "field": {
                "Column": {
                  "Expression": {
                    "SourceRef": {
                      "Entity": "Budget"
                    }
                  },
                  "Property": "Area lvl 2"
                }
              },
              "queryRef": "Budget.Area Path Lvl 2",
              "nativeQueryRef": "Area Path Lvl 2",
              "active": true
            }
          ]
        },
        "Y": {
          "projections": [
            {
              "field": {
                "Measure": {
                  "Expression": {
                    "SourceRef": {
                      "Entity": "Budget"
                    }
                  },
                  "Property": "Remaining budget (CY)"
                }
              },
              "queryRef": "Budget.Remaining budget (CY)",
              "nativeQueryRef": "Remaining budget (CY)"
            }
          ]
        }
      },
      "sortDefinition": {
        "sort": [
          {
            "field": {
              "Measure": {
                "Expression": {
                  "SourceRef": {
                    "Entity": "Budget"
                  }
                },
                "Property": "Remaining budget (CY)"
              }
            },
            "direction": "Descending"
          }
        ],
        "isDefaultSort": true
      }
    },
    "objects": {
      "labels": [
        {
          "properties": {
            "labelStyle": {
              "expr": {
                "Literal": {
                  "Value": "'Data'"
                }
              }
            }
          }
        }
      ],
      "legend": [
        {
          "properties": {
            "show": {
              "expr": {
                "Literal": {
                  "Value": "true"
                }
              }
            },
            "position": {
              "expr": {
                "Literal": {
                  "Value": "'Top'"
                }
              }
            },
            "showTitle": {
              "expr": {
                "Literal": {
                  "Value": "false"
                }
              }
            }
          }
        }
      ]
    },
    "visualContainerObjects": {
      "title": [
        {
          "properties": {
            "show": {
              "expr": {
                "Literal": {
                  "Value": "false"
                }
              }
            },
            "text": {
              "expr": {
                "Literal": {
                  "Value": "''"
                }
              }
            }
          }
        }
      ]
    },
    "drillFilterOtherVisuals": true
  },
  "filterConfig": {
    "filters": [
      {
        "name": "Filterf734571009bbea940c70",
        "field": {
          "Column": {
            "Expression": {
              "SourceRef": {
                "Entity": "DevOps_Timesheets"
              }
            },
            "Property": "Comment"
          }
        },
        "type": "Categorical",
        "howCreated": "User",
        "isHiddenInViewMode": true
      },
      {
        "name": "Filtere6ef7d3ae8c8abace217",
        "field": {
          "Column": {
            "Expression": {
              "SourceRef": {
                "Entity": "DevOps_Timesheets"
              }
            },
            "Property": "RecordDate"
          }
        },
        "type": "Categorical",
        "howCreated": "User",
        "isHiddenInViewMode": true
      },
      {
        "name": "Filter97dc7be6d81635007803",
        "field": {
          "Column": {
            "Expression": {
              "SourceRef": {
                "Entity": "Power BI - All projects"
              }
            },
            "Property": "State"
          }
        },
        "type": "Categorical",
        "howCreated": "User",
        "isHiddenInViewMode": true
      },
      {
        "name": "Filterfedbe1d2be9d618927fc",
        "field": {
          "Column": {
            "Expression": {
              "SourceRef": {
                "Entity": "Power BI - All projects"
              }
            },
            "Property": "Title"
          }
        },
        "type": "Categorical",
        "howCreated": "User",
        "isHiddenInViewMode": true
      },
      {
        "name": "Filter3221213e3397fafa4df1",
        "field": {
          "Column": {
            "Expression": {
              "SourceRef": {
                "Entity": "Power BI - All projects"
              }
            },
            "Property": "Link"
          }
        },
        "type": "Categorical",
        "howCreated": "User",
        "isHiddenInViewMode": true
      },
      {
        "name": "Filter56a7e6964c43b57685ae",
        "field": {
          "Measure": {
            "Expression": {
              "SourceRef": {
                "Entity": "DevOps_Timesheets"
              }
            },
            "Property": "Time"
          }
        },
        "type": "Advanced",
        "howCreated": "User",
        "isHiddenInViewMode": true
      }
    ]
  }
}

=== dbru540/powerbi-mcp-designer/example/Focus.Report/definition/pages/ReportSectiond5a9be7e10078cea179d/visuals/b6dd4ee3c994c69c3dd7/visual.json
{
  "$schema": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualContainer/2.4.0/schema.json",
  "name": "b6dd4ee3c994c69c3dd7",
  "position": {
    "x": 270.28529027125222,
    "y": 92.88390387688483,
    "z": 9000,
    "height": 23.076923076923077,
    "width": 86.92307692307692,
    "tabOrder": 9000
  },
  "visual": {
    "visualType": "image",
    "objects": {
      "general": [
        {
          "properties": {
            "imageUrl": {
              "expr": {
                "ResourcePackageItem": {
                  "PackageName": "RegisteredResources",
                  "PackageType": 1,
                  "ItemName": "2025-06-10_14-59-0329693445723803157.jpg"
                }
              }
            }
          }
        }
      ]
    },
    "visualContainerObjects": {
      "visualHeader": [
        {
          "properties": {
            "show": {
              "expr": {
                "Literal": {
                  "Value": "false"
                }
              }
            }
          }
        }
      ]
    },
    "drillFilterOtherVisuals": true
  },
  "howCreated": "InsertVisualButton"
}

=== dbru540/powerbi-mcp-designer/example/Focus.Report/definition/pages/ReportSectiond5a9be7e10078cea179d/visuals/b4e43d3f14fb36e19a40/visual.json
{
  "$schema": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualContainer/2.4.0/schema.json",
  "name": "b4e43d3f14fb36e19a40",
  "position": {
    "x": 36,
    "y": 519,
    "z": 13000,
    "height": 23,
    "width": 87,
    "tabOrder": 13000
  },
  "visual": {
    "visualType": "image",
    "objects": {
      "general": [
        {
          "properties": {
            "imageUrl": {
              "expr": {
                "ResourcePackageItem": {
                  "PackageName": "RegisteredResources",
                  "PackageType": 1,
                  "ItemName": "2025-06-10_14-59-0329693445723803157.jpg"
                }
              }
            }
          }
        }
      ]
    },
    "visualContainerObjects": {
      "visualHeader": [
        {
          "properties": {
            "show": {
              "expr": {
                "Literal": {
                  "Value": "false"
                }
              }
            }
          }
        }
      ]
    },
    "drillFilterOtherVisuals": true
  },
  "howCreated": "InsertVisualButton"
}

=== dbru540/powerbi-mcp-designer/example/Focus.Report/definition/pages/c0125211305100a1b504/visuals/e033a49684aa4b079c12/visual.json
{
  "$schema": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualContainer/2.4.0/schema.json",
  "name": "e033a49684aa4b079c12",
  "position": {
    "x": 35.454545454545453,
    "y": 290.90909090909088,
    "z": 2000,
    "height": 207.27272727272725,
    "width": 335.45454545454544,
    "tabOrder": 6000
  },
  "visual": {
    "visualType": "pieChart",
    "query": {
      "queryState": {
        "Category": {
          "projections": [
            {
              "field": {
                "Column": {
                  "Expression": {
                    "SourceRef": {
                      "Entity": "Power BI - All projects"
                    }
                  },
                  "Property": "Area lvl 2"
                }
              },
              "queryRef": "Power BI - All projects.Area lvl 2",
              "nativeQueryRef": "Area lvl 21",
              "active": true
            },
            {
              "field": {
                "Column": {
                  "Expression": {
                    "SourceRef": {
                      "Entity": "Power BI - All projects"
                    }
                  },
                  "Property": "Area lvl 3"
                }
              },
              "queryRef": "Power BI - All projects.Area lvl 3",
              "nativeQueryRef": "Area lvl 3",
              "active": false
            }
          ]
        },
        "Y": {
          "projections": [
            {
              "field": {
                "Measure": {
                  "Expression": {
                    "SourceRef": {
                      "Entity": "DevOps_Timesheets"
                    }
                  },
                  "Property": "Time Final"
                }
              },
              "queryRef": "DevOps_Timesheets.Time Final",
              "nativeQueryRef": "Time",
              "displayName": "Time"
            }
          ]
        }
      },
      "sortDefinition": {
        "sort": [
          {
            "field": {
              "Measure": {
                "Expression": {
                  "SourceRef": {
                    "Entity": "DevOps_Timesheets"
                  }
                },
                "Property": "Time Final"
              }
            },
            "direction": "Descending"
          }
        ],
        "isDefaultSort": true
      }
    },
    "objects": {
      "labels": [
        {
          "properties": {
            "labelStyle": {
              "expr": {
                "Literal": {
                  "Value": "'Percent of total'"
                }
              }
            },
            "percentageLabelPrecision": {
              "expr": {
                "Literal": {
                  "Value": "0L"
                }
              }
            }
          }
        }
      ]
    },
    "visualContainerObjects": {
      "background": [
        {
          "properties": {
            "transparency": {
              "expr": {
                "Literal": {
                  "Value": "100D"
                }
              }
            }
          }
        }
      ],
      "visualHeader": [
        {
          "properties": {
            "show": {
              "expr": {
                "Literal": {
                  "Value": "true"
                }
              }
            }
          }
        }
      ],
      "title": [
        {
          "properties": {
            "show": {
              "expr": {
                "Literal": {
                  "Value": "false"
                }
              }
            }
          }
        }
      ]
    },
    "drillFilterOtherVisuals": true
  },
  "filterConfig": {
    "filters": [
      {
        "name": "Filterc439d448cf2cfddaadd7",
        "field": {
          "Measure": {
            "Expression": {
              "SourceRef": {
                "Entity": "DevOps_Timesheets"
              }
            },
            "Property": "Time"
          }
        },
        "type": "Advanced",
        "howCreated": "User",
        "isHiddenInViewMode": true
      }
    ]
  }
}
