=== dbru540/powerbi-mcp-designer/powerbi_mcp/validation/schemas/fabric__item__report__definition__visualContainer__2.4.0__schema.json
{
  "$id": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualContainer/2.4.0/schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Visual container",
  "description": "Defines a single visual or visual group on a report page.",
  "type": "object",
  "properties": {
    "$schema": {
      "description": "Defines the schema to use for an item.",
      "type": "string",
      "const": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualContainer/2.4.0/schema.json"
    },
    "name": {
      "description": "A unique identifier for the visual across the whole page.",
      "maxLength": 50,
      "type": "string"
    },
    "position": {
      "$ref": "#/definitions/VisualContainerPosition",
      "description": "Defines where the visual is position on the page and how big it should be, along\nwith z-index (stacking) for that visual.\nAlso defines the order in which visuals are navigated when using just keyboard (tabOrder)."
    },
    "visual": {
      "description": "Defines a chart to be shown inside of this container.",
      "$ref": "../../visualConfiguration/2.2.0/schema-embedded.json"
    },
    "visualGroup": {
      "description": "Defines that this container should be used as a grouping container.",
      "$ref": "#/definitions/VisualGroupConfig"
    },
    "parentGroupName": {
      "description": "Name of the parent group (visual container), if it is part of one.",
      "type": "string"
    },
    "filterConfig": {
      "description": "Filters that apply to all this visual - on top of the filters defined for the report and page.",
      "$ref": "../../filterConfiguration/1.2.0/schema-embedded.json"
    },
    "isHidden": {
      "description": "Marks the visual as hidden.",
      "type": "boolean"
    },
    "annotations": {
      "description": "Additional information to be saved (for example comments, readme, etc) for this visual.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Annotation"
      }
    },
    "howCreated": {
      "description": "Source of creation of this visual.",
      "type": "string",
      "anyOf": [
        {
          "const": "Default",
          "description": "Used when it doesn't fall in any of the buckets below."
        },
        {
          "const": "Copilot",
          "description": "Created by copilot."
        },
        {
          "const": "CheckboxTickedInFieldList",
          "description": "Selecting data from field list."
        },
        {
          "const": "DraggedToCanvas",
          "description": "Dragging data from field list to the canvas."
        },
        {
          "const": "VisualTypeIconClicked",
          "description": "Clicking a specific visual icon in visualizations list."
        },
        {
          "const": "DraggedToFieldWell",
          "description": "Dragging data from field list to field wells."
        },
        {
          "const": "InsertVisualButton",
          "description": "Clicking the \"Insert visual\" button in ribbon."
        },
        {
          "const": "WhatIfParameterControl",
          "description": "Automatically by what-if parameter."
        },
        {
          "const": "QnaAppBar",
          "description": "Ask a question in app bar."
        },
        {
          "const": "QnaDoubleClick",
          "description": "Double clicking on the canvas to generate a Q&A visual."
        },
        {
          "const": "QnaKeyboardShortcut",
          "description": "Use keyboard shortcut for Q&A visual."
        },
        {
          "const": "FieldParameterControl",
          "description": "Automatically by field parameters."
        },
        {
          "const": "CanvasBackgroundContextMenu",
          "description": "Using on-object context menu for the canvas."
        },
        {
          "const": "ContextMenuPaste",
          "description": "By using paste from context manu."
        },
        {
          "const": "CopyPaste",
          "description": "By using copy paste."
        },
        {
          "const": "SummarizeVisualContainer",
          "description": "By using context menu Summarize."
        }
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "$schema",
    "name",
    "position"
  ],
  "definitions": {
    "VisualContainerPosition": {
      "type": "object",
      "properties": {
        "x": {
          "description": "Horizontal position of the left edge of the visual.\nShould be between 0 and width of the containing page.",
          "type": "number"
        },
        "y": {
          "description": "Vertical position of the top edge of the visual.\nShould be between 0 and height of the containing page.",
          "type": "number"
        },
        "z": {
          "description": "Defines the stacking order for the visual.\nHigher z-index visuals are shown on top of the lower ones.",
          "type": "number"
        },
        "height": {
          "description": "Height of the visual.\ny + height should be less than the height of the containing page.",
          "type": "number"
        },
        "width": {
          "description": "Width of the visual.\nx + width should be less than the width of the containing page.",
          "type": "number"
        },
        "tabOrder": {
          "description": "Defines the selection order for this visual when using keyboard (tab key)\nto navigate the visuals on the containing page.",
          "type": "number"
        },
        "angle": {
          "type": "number"
        }
      },
      "additionalProperties": false,
      "required": [
        "height",
        "width",
        "x",
        "y"
      ]
    },
    "VisualGroupConfig": {
      "type": "object",
      "properties": {
        "displayName": {
          "description": "Display name for the group.",
          "type": "string"
        },
        "groupMode": {
          "$ref": "#/definitions/GroupLayoutMode",
          "description": "Defines how the visuals are organized inside this group."
        },
        "objects": {
          "description": "Specifies the formatting to be set for different \"objects\" of this group.",
          "$ref": "#/definitions/VisualGroupFormattingObjects"
        }
      },
      "additionalProperties": false,
      "required": [
        "displayName",
        "groupMode"
      ]
    },
    "GroupLayoutMode": {
      "type": "string",
      "anyOf": [
        {
          "const": "ScaleMode",
          "description": "Visuals are scaled as group resizes to preserve the aspect ratio and avoid scrolling."
        },
        {
          "const": "ScrollMode",
          "description": "Visuals are not resized, if the containing box for group is smaller than the space\nneeded for visuals, then scrollbar is added."
        }
      ]
    },
    "VisualGroupFormattingObjects": {
      "type": "object",
      "properties": {
        "background": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "selector": {
                "description": "Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.",
                "$ref": "../../formattingObjectDefinitions/1.4.0/schema.json#/definitions/Selector"
              },
              "properties": {
                "$ref": "../../visualConfiguration/2.2.0/schema-embedded.json#/definitions/Background",
                "description": "Describes the properties of the object to apply formatting changes to."
              }
            },
            "additionalProperties": false,
            "required": [
              "properties"
            ]
          }
        },
        "lockAspect": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "selector": {
                "description": "Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.",
                "$ref": "../../formattingObjectDefinitions/1.4.0/schema.json#/definitions/Selector"
              },
              "properties": {
                "$ref": "../../visualConfiguration/2.2.0/schema-embedded.json#/definitions/LockAspect",
                "description": "Describes the properties of the object to apply formatting changes to."
              }
            },
            "additionalProperties": false,
            "required": [
              "properties"
            ]
          }
        },
        "general": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "selector": {
                "description": "Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.",
                "$ref": "../../formattingObjectDefinitions/1.4.0/schema.json#/definitions/Selector"
              },
              "properties": {
                "$ref": "#/definitions/VisualGroupGeneralFormattingObjects",
                "description": "Describes the properties of the object to apply formatting changes to."
              }
            },
            "additionalProperties": false,
            "required": [
              "properties"
            ]
          }
        }
      },
      "additionalProperties": false
    },
    "VisualGroupGeneralFormattingObjects": {
      "type": "object",
      "properties": {
        "x": {},
        "y": {},
        "width": {},
        "height": {},
        "altText": {}
      },
      "additionalProperties": false
    },
    "Annotation": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Unique name for the annotation.",
          "type": "string"
        },
        "value": {
          "description": "A value for this annotation.",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "value"
      ]
    }
  },
  "oneOf": [
    {
      "required": [
        "visual"
      ]
    },
    {
      "required": [
        "visualGroup"
      ]
    }
  ]
}

=== dbru540/powerbi-mcp-designer/example/Focus.Report/definition/pages/a612292011b1e00129db/visuals/21da098b97697dcd36d5/visual.json
{
  "$schema": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualContainer/2.4.0/schema.json",
  "name": "21da098b97697dcd36d5",
  "position": {
    "x": 52.772727272727259,
    "y": 74.47727272727272,
    "z": 2000,
    "height": 52.72727272727272,
    "width": 59.999999999999993,
    "tabOrder": 0
  },
  "visual": {
    "visualType": "image",
    "objects": {
      "general": [
        {
          "properties": {
            "imageUrl": {
              "expr": {
                "ResourcePackageItem": {
                  "PackageName": "RegisteredResources",
                  "PackageType": 1,
                  "ItemName": "2025-06-11_16-50-335217148787700067.jpg"
                }
              }
            }
          }
        }
      ]
    },
    "drillFilterOtherVisuals": true
  },
  "howCreated": "InsertVisualButton"
}

=== dbru540/powerbi-mcp-designer/example/Focus.Report/definition/pages/320d197c26a960f2dbde/visuals/d1baf51bc4cf1661e9fc/visual.json
{
  "$schema": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualContainer/2.4.0/schema.json",
  "name": "d1baf51bc4cf1661e9fc",
  "position": {
    "x": 939.41176470588243,
    "y": 214.1764705882353,
    "z": 9000,
    "height": 72.3529411764706,
    "width": 13.529411764705882,
    "tabOrder": 9000
  },
  "visual": {
    "visualType": "shape",
    "objects": {
      "shape": [
        {
          "properties": {
            "tileShape": {
              "expr": {
                "Literal": {
                  "Value": "'line'"
                }
              }
            }
          }
        }
      ],
      "rotation": [
        {
          "properties": {
            "shapeAngle": {
              "expr": {
                "Literal": {
                  "Value": "0L"
                }
              }
            },
            "angle": {
              "expr": {
                "Literal": {
                  "Value": "90D"
                }
              }
            }
          }
        }
      ],
      "fill": [
        {
          "properties": {
            "fillColor": {
              "solid": {
                "color": {
                  "expr": {
                    "Literal": {
                      "Value": "'#0FB3B3'"
                    }
                  }
                }
              }
            }
          },
          "selector": {
            "id": "default"
          }
        }
      ],
      "outline": [
        {
          "properties": {
            "lineColor": {
              "solid": {
                "color": {
                  "expr": {
                    "Literal": {
                      "Value": "'#0FB3B3'"
                    }
                  }
                }
              }
            },
            "weight": {
              "expr": {
                "Literal": {
                  "Value": "1D"
                }
              }
            }
          },
          "selector": {
            "id": "default"
          }
        }
      ]
    },
    "visualContainerObjects": {
      "visualHeader": [
        {
          "properties": {
            "show": {
              "expr": {
                "Literal": {
                  "Value": "false"
                }
              }
            }
          }
        }
      ]
    },
    "drillFilterOtherVisuals": true
  },
  "howCreated": "InsertVisualButton"
}

=== dbru540/powerbi-mcp-designer/example/Focus.Report/definition/pages/ReportSectiona73ab10ffb0f4759f223/visuals/5483ee8f2ed2ba926255/visual.json
{
  "$schema": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualContainer/2.4.0/schema.json",
  "name": "5483ee8f2ed2ba926255",
  "position": {
    "x": 35,
    "y": 498,
    "z": 5000,
    "height": 142,
    "width": 336,
    "tabOrder": 3000
  },
  "visual": {
    "visualType": "clusteredBarChart",
    "query": {
      "queryState": {
        "Category": {
          "projections": [
            {
              "field": {
                "Column": {
                  "Expression": {
                    "SourceRef": {
                      "Entity": "DevOps_Timesheets"
                    }
                  },
                  "Property": "Team Member"
                }
              },
              "queryRef": "DevOps_Timesheets.Team Member",
              "nativeQueryRef": "Team Member",
              "active": true
            }
          ]
        },
        "Y": {
          "projections": [
            {
              "field": {
                "Measure": {
                  "Expression": {
                    "SourceRef": {
                      "Entity": "DevOps_Timesheets"
                    }
                  },
                  "Property": "Time Final"
                }
              },
              "queryRef": "DevOps_Timesheets.Time Final",
              "nativeQueryRef": "Time",
              "displayName": "Time"
            }
          ]
        }
      },
      "sortDefinition": {
        "sort": [
          {
            "field": {
              "Measure": {
                "Expression": {
                  "SourceRef": {
                    "Entity": "DevOps_Timesheets"
                  }
                },
                "Property": "Time Final"
              }
            },
            "direction": "Descending"
          }
        ],
        "isDefaultSort": true
      }
    },
    "objects": {
      "labels": [
        {
          "properties": {
            "show": {
              "expr": {
                "Literal": {
                  "Value": "true"
                }
              }
            },
            "labelPrecision": {
              "expr": {
                "Literal": {
                  "Value": "2L"
                }
              }
            }
          }
        }
      ],
      "categoryAxis": [
        {
          "properties": {
            "concatenateLabels": {
              "expr": {
                "Literal": {
                  "Value": "true"
                }
              }
            },
            "showAxisTitle": {
              "expr": {
                "Literal": {
                  "Value": "false"
                }
              }
            }
          }
        }
      ],
      "valueAxis": [
        {
          "properties": {
            "labelPrecision": {
              "expr": {
                "Literal": {
                  "Value": "0L"
                }
              }
            },
            "showAxisTitle": {
              "expr": {
                "Literal": {
                  "Value": "false"
                }
              }
            }
          }
        }
      ],
      "zoom": [
        {
          "properties": {
            "show": {
              "expr": {
                "Literal": {
                  "Value": "false"
                }
              }
            }
          }
        }
      ]
    },
    "visualContainerObjects": {
      "stylePreset": [
        {
          "properties": {
            "name": {
              "expr": {
                "Literal": {
                  "Value": "'Default'"
                }
              }
            }
          }
        }
      ],
      "title": [
        {
          "properties": {
            "show": {
              "expr": {
                "Literal": {
                  "Value": "false"
                }
              }
            }
          }
        }
      ],
      "visualHeader": [
        {
          "properties": {
            "show": {
              "expr": {
                "Literal": {
                  "Value": "true"
                }
              }
            }
          }
        }
      ],
      "visualTooltip": [
        {
          "properties": {
            "show": {
              "expr": {
                "Literal": {
                  "Value": "false"
                }
              }
            }
          }
        }
      ]
    },
    "drillFilterOtherVisuals": true
  },
  "filterConfig": {
    "filters": [
      {
        "name": "Filtercf84f257a5eebb57fcdb",
        "field": {
          "Measure": {
            "Expression": {
              "SourceRef": {
                "Entity": "DevOps_Timesheets"
              }
            },
            "Property": "Time"
          }
        },
        "type": "Advanced",
        "howCreated": "User",
        "isHiddenInViewMode": true
      },
      {
        "name": "6d96b7734a5fb8449b88",
        "field": {
          "Measure": {
            "Expression": {
              "SourceRef": {
                "Entity": "DevOps_Timesheets"
              }
            },
            "Property": "Time Final"
          }
        },
        "type": "Advanced",
        "isHiddenInViewMode": true
      },
      {
        "name": "9ef3a548fc35664b9627",
        "field": {
          "Column": {
            "Expression": {
              "SourceRef": {
                "Entity": "DevOps_Timesheets"
              }
            },
            "Property": "Team Member"
          }
        },
        "type": "Categorical",
        "isHiddenInViewMode": true
      }
    ]
  }
}

=== dbru540/powerbi-mcp-designer/example/Focus.Report/definition/pages/ReportSectiona73ab10ffb0f4759f223/visuals/080c3bdfee4f864670b1/visual.json
{
  "$schema": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualContainer/2.4.0/schema.json",
  "name": "080c3bdfee4f864670b1",
  "position": {
    "x": 55.04545454545454,
    "y": 198.84090909090915,
    "z": 3000,
    "height": 66,
    "width": 90,
    "tabOrder": 8000
  },
  "visual": {
    "visualType": "slicer",
    "query": {
      "queryState": {
        "Values": {
          "projections": [
            {
              "field": {
                "Column": {
                  "Expression": {
                    "SourceRef": {
                      "Entity": "TimeType"
                    }
                  },
                  "Property": "Time"
                }
              },
              "queryRef": "TimeType.Time",
              "active": true
            }
          ]
        }
      },
      "sortDefinition": {
        "isDefaultSort": true
      }
    },
    "objects": {
      "data": [
        {
          "properties": {
            "startDate": {
              "expr": {
                "Literal": {
                  "Value": "datetime'2022-11-01T00:00:00'"
                }
              }
            },
            "endDate": {
              "expr": {
                "Literal": {
                  "Value": "datetime'2022-11-30T00:00:00'"
                }
              }
            },
            "mode": {
              "expr": {
                "Literal": {
                  "Value": "'Basic'"
                }
              }
            }
          }
        }
      ],
      "header": [
        {
          "properties": {
            "show": {
              "expr": {
                "Literal": {
                  "Value": "false"
                }
              }
            },
            "text": {
              "expr": {
                "Literal": {
                  "Value": "'Period range'"
                }
              }
            }
          }
        }
      ],
      "slider": [
        {
          "properties": {
            "show": {
              "expr": {
                "Literal": {
                  "Value": "false"
                }
              }
            }
          }
        }
      ],
      "general": [
        {
          "properties": {
            "filter": {
              "filter": {
                "Version": 2,
                "From": [
                  {
                    "Name": "t",
                    "Entity": "TimeType",
                    "Type": 0
                  }
                ],
                "Where": [
                  {
                    "Condition": {
                      "In": {
                        "Expressions": [
                          {
                            "Column": {
                              "Expression": {
                                "SourceRef": {
                                  "Source": "t"
                                }
                              },
                              "Property": "Time"
                            }
                          }
                        ],
                        "Values": [
                          [
                            {
                              "Literal": {
                                "Value": "'In €'"
                              }
                            }
                          ]
                        ]
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      ],
      "date": [
        {
          "properties": {
            "textSize": {
              "expr": {
                "Literal": {
                  "Value": "8D"
                }
              }
            }
          }
        }
      ],
      "selection": [
        {
          "properties": {
            "strictSingleSelect": {
              "expr": {
                "Literal": {
                  "Value": "true"
                }
              }
            }
          }
        }
      ]
    },
    "visualContainerObjects": {
      "title": [
        {
          "properties": {
            "show": {
              "expr": {
                "Literal": {
                  "Value": "false"
                }
              }
            },
            "text": {
              "expr": {
                "Literal": {
                  "Value": "'Display mode'"
                }
              }
            },
            "alignment": {
              "expr": {
                "Literal": {
                  "Value": "'center'"
                }
              }
            },
            "fontSize": {
              "expr": {
                "Literal": {
                  "Value": "11D"
                }
              }
            },
            "background": {
              "solid": {
                "color": {
                  "expr": {
                    "ThemeDataColor": {
                      "ColorId": 3,
                      "Percent": 0
                    }
                  }
                }
              }
            }
          }
        }
      ],
      "visualHeader": [
        {
          "properties": {
            "show": {
              "expr": {
                "Literal": {
                  "Value": "false"
                }
              }
            }
          }
        }
      ],
      "border": [
        {
          "properties": {
            "show": {
              "expr": {
                "Literal": {
                  "Value": "false"
                }
              }
            }
          }
        }
      ],
      "dropShadow": [
        {
          "properties": {
            "show": {
              "expr": {
                "Literal": {
                  "Value": "false"
                }
              }
            }
          }
        }
      ],
      "background": [
        {
          "properties": {
            "show": {
              "expr": {
                "Literal": {
                  "Value": "false"
                }
              }
            }
          }
        }
      ]
    },
    "syncGroup": {
      "groupName": "Time",
      "fieldChanges": true,
      "filterChanges": true
    },
    "drillFilterOtherVisuals": true
  },
  "filterConfig": {
    "filters": [
      {
        "name": "Filter43427982a391d9b99cc1",
        "field": {
          "Column": {
            "Expression": {
              "SourceRef": {
                "Entity": "TimeType"
              }
            },
            "Property": "Time"
          }
        },
        "type": "Categorical",
        "isHiddenInViewMode": true
      }
    ]
  }
}
